export const routes = {
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  transactions: "/transactions",
  budgets: "/budgets",
  goals: "/goals",
  reports: "/reports",
  insights: "/insights",
  rules: "/rules",
  recurring: "/recurring",
  accounts: "/accounts",
  settings: "/settings",
} as const;
