name: Build and deploy ASP.Net Core app to Azure Web App - track-my-money-api

on:
  push:
    branches:
      - main
    paths:
      - "personal-finance-tracker-backend/**"
      - ".github/workflows/main_track-my-money-api.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore PersonalFinance.sln
        working-directory: ./personal-finance-tracker-backend

      - name: Build with dotnet
        run: dotnet build src/PersonalFinance.Api/PersonalFinance.Api.csproj --configuration Release --no-restore
        working-directory: ./personal-finance-tracker-backend

      - name: dotnet publish
        run: dotnet publish src/PersonalFinance.Api/PersonalFinance.Api.csproj -c Release --no-build -o ./publish
        working-directory: ./personal-finance-tracker-backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: personal-finance-tracker-backend/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_98A179BA8ECE4D80AE613ED9D972C530 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_138716F0CD6F468BAF8C0730A005DA6A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DE6C46F57265427993F18159658251A1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'track-my-money-api'
          slot-name: 'Production'
          package: ./publish
